//-----------------------------------------------------------------------
// <copyright file=" BbsAnswer.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BbsAnswer.cs
// * history : Created by T4 09/28/2019 17:26:54
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    /// <summary>
    /// BbsAnswer Entity Model
    /// </summary>
    [Table("bbs_answer")]
    public partial class BbsAnswer
    {
        /// <summary>
        /// 唯一编号 唯一编号
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 问题编号 问题编号
        /// </summary>
        public string QuestionGuid { get; set; }

        /// <summary>
        /// 用户编号 用户编号
        /// </summary>
        public string UserGuid { get; set; }

        /// <summary>
        /// 是否采纳 是否采纳
        /// </summary>
        public bool IsAdopt { get; set; }

        /// <summary>
        /// 答案内容 答案内容
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 回答时间 回答时间
        /// </summary>
        public DateTime AddTime { get; set; }

    }
}
