//-----------------------------------------------------------------------
// <copyright file=" BbsNotice.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BbsNotice.cs
// * history : Created by T4 09/28/2019 17:26:54
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    /// <summary>
    /// BbsNotice Entity Model
    /// </summary>
    [Table("bbs_notice")]
    public partial class BbsNotice
    {
        /// <summary>
        /// 唯一编号 唯一编号
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 用户编号 用户编号
        /// </summary>
        [Key]
        public string UserGuid { get; set; }

        /// <summary>
        /// 消息类型 消息类型
        /// </summary>
        [Key]
        public int Types { get; set; }

        /// <summary>
        /// 消息内容 消息内容
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 阅读状态 阅读状态
        /// </summary>
        [Key]
        public bool IsRead { get; set; }

        /// <summary>
        /// 发送时间 发送时间
        /// </summary>
        [Key]
        public DateTime AddTime { get; set; }

    }
}
