//-----------------------------------------------------------------------
// <copyright file=" CmsColumn.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsColumn.cs
// * history : Created by T4 09/28/2019 17:26:54
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    /// <summary>
    /// CmsColumn Entity Model
    /// </summary>
    [Table("cms_column")]
    public partial class CmsColumn
    {
        /// <summary>
        /// 自动递增
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// 栏目编号
        /// </summary>
        public string Number { get; set; }

        /// <summary>
        /// 栏目标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 英文栏位名称
        /// </summary>
        public string EnTitle { get; set; }

        /// <summary>
        /// 栏位副标题
        /// </summary>
        public string SubTitle { get; set; }

        /// <summary>
        /// 父栏目
        /// </summary>
        public int ParentId { get; set; }

        /// <summary>
        /// 栏位集合
        /// </summary>
        public string ClassList { get; set; }

        /// <summary>
        /// 栏位等级
        /// </summary>
        public int ClassLayer { get; set; }

        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }

        /// <summary>
        /// 栏目类型
        /// </summary>
        public int TypeID { get; set; }

        /// <summary>
        /// 栏位属性
        /// </summary>
        public string Attr { get; set; }

        /// <summary>
        /// 模板ID
        /// </summary>
        public int TempId { get; set; }

        /// <summary>
        /// 模板名称
        /// </summary>
        public string TempName { get; set; }

        /// <summary>
        /// 模板地址
        /// </summary>
        public string TempUrl { get; set; }

        /// <summary>
        /// 栏位图片
        /// </summary>
        public string ImgUrl { get; set; }

        /// <summary>
        /// 外部链接地址
        /// </summary>
        public string LinkUrl { get; set; }

        /// <summary>
        /// 移动端链接地址
        /// </summary>
        public string WapLinkUrl { get; set; }

        /// <summary>
        /// 是否顶部显示
        /// </summary>
        public bool IsTopShow { get; set; }

        /// <summary>
        /// 是否手机端展示
        /// </summary>
        public bool IsWapShow { get; set; }

        /// <summary>
        /// 关键词
        /// </summary>
        public string KeyWord { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// 内容
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 站点ID
        /// </summary>
        public string SiteGuid { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime UpdateDate { get; set; }

    }
}
