//-----------------------------------------------------------------------
// <copyright file=" CmsDownload.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsDownload.cs
// * history : Created by T4 09/28/2019 17:26:54
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    /// <summary>
    /// CmsDownload Entity Model
    /// </summary>
    [Table("cms_download")]
    public partial class CmsDownload
    {
        /// <summary>
        /// 
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// 下载所属类型
        /// </summary>
        public int ColumnId { get; set; }

        /// <summary>
        /// 下载标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 下载副标题
        /// </summary>
        public string SubTitle { get; set; }

        /// <summary>
        /// 文件地址
        /// </summary>
        public string FileUrl { get; set; }

        /// <summary>
        /// 文件类型
        /// </summary>
        public string FileType { get; set; }

        /// <summary>
        /// 文件大小
        /// </summary>
        public string FileSize { get; set; }

        /// <summary>
        /// 下载数量
        /// </summary>
        public int DownSum { get; set; }

        /// <summary>
        /// 访问数
        /// </summary>
        public int Hits { get; set; }

        /// <summary>
        /// 权重
        /// </summary>
        public int Sort { get; set; }

        /// <summary>
        /// 适用系统
        /// </summary>
        public string IsSystem { get; set; }

        /// <summary>
        /// 软件类型
        /// </summary>
        public string IsCharge { get; set; }

        /// <summary>
        /// 图片地址
        /// </summary>
        public string ImgUrl { get; set; }

        /// <summary>
        /// 缩略图地址
        /// </summary>
        public string ThumImg { get; set; }

        /// <summary>
        /// 是否置顶
        /// </summary>
        public bool IsTop { get; set; }

        /// <summary>
        /// 是否评论
        /// </summary>
        public bool IsComment { get; set; }

        /// <summary>
        /// 状态
        /// </summary>
        public bool Audit { get; set; }

        /// <summary>
        /// 是否有外链
        /// </summary>
        public bool IsLink { get; set; }

        /// <summary>
        /// 外链地址
        /// </summary>
        public string LinkUrl { get; set; }

        /// <summary>
        /// 标签
        /// </summary>
        public string Tag { get; set; }

        /// <summary>
        /// 简介
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// 详细描述
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime EditDate { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime AddDate { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string SiteGuid { get; set; }

    }
}
