//-----------------------------------------------------------------------
// <copyright file=" CmsImage.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsImage.cs
// * history : Created by T4 09/28/2019 17:26:54
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    /// <summary>
    /// CmsImage Entity Model
    /// </summary>
    [Table("cms_image")]
    public partial class CmsImage
    {
        /// <summary>
        /// 
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 所属栏目Guid
        /// </summary>
        public string TheGuid { get; set; }

        /// <summary>
        /// 图片类型，一个栏目可有多个图片类型
        /// </summary>
        public int Types { get; set; }

        /// <summary>
        /// 图片名称
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 图片原图
        /// </summary>
        public string ImgBig { get; set; }

        /// <summary>
        /// 图片缩略图
        /// </summary>
        public string ImgSmall { get; set; }

        /// <summary>
        /// 文件类型
        /// </summary>
        public string ImgType { get; set; }

        /// <summary>
        /// 文件大小
        /// </summary>
        public long ImgSize { get; set; }

        /// <summary>
        /// 是否为封面
        /// </summary>
        public bool IsCover { get; set; }

        /// <summary>
        /// 排序字段
        /// </summary>
        public int Sort { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime AddDate { get; set; }

    }
}
