//-----------------------------------------------------------------------
// <copyright file=" CmsSite.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsSite.cs
// * history : Created by T4 09/28/2019 17:26:54
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    /// <summary>
    /// CmsSite Entity Model
    /// </summary>
    [Table("cms_site")]
    public partial class CmsSite
    {
        /// <summary>
        /// 
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 系统ID
        /// </summary>
        public int SysId { get; set; }

        /// <summary>
        /// 网站名称
        /// </summary>
        public string SiteName { get; set; }

        /// <summary>
        /// 网站域名
        /// </summary>
        public string SiteUrl { get; set; }

        /// <summary>
        /// 网站Logo
        /// </summary>
        public string SiteLogo { get; set; }

        /// <summary>
        /// 网站描述
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// 公司电话
        /// </summary>
        public string SiteTel { get; set; }

        /// <summary>
        /// 公司传真
        /// </summary>
        public string SiteFax { get; set; }

        /// <summary>
        /// 公司人事邮箱
        /// </summary>
        public string SiteEmail { get; set; }

        /// <summary>
        /// 公司客服QQ
        /// </summary>
        public string QQ { get; set; }

        /// <summary>
        /// 微信公众号图片
        /// </summary>
        public string WeiXin { get; set; }

        /// <summary>
        /// 微博链接地址或者二维码
        /// </summary>
        public string WeiBo { get; set; }

        /// <summary>
        /// 公司地址
        /// </summary>
        public string SiteAddress { get; set; }

        /// <summary>
        /// 网站备案号其它等信息
        /// </summary>
        public string SiteCode { get; set; }

        /// <summary>
        /// 网站SEO标题
        /// </summary>
        public string SeoTitle { get; set; }

        /// <summary>
        /// 网站SEO关键字
        /// </summary>
        public string SeoKey { get; set; }

        /// <summary>
        /// 网站SEO描述
        /// </summary>
        public string SeoDescribe { get; set; }

        /// <summary>
        /// 网站版权等信息
        /// </summary>
        public string SiteCopyright { get; set; }

        /// <summary>
        /// 网站开启关闭状态
        /// </summary>
        public bool Status { get; set; }

        /// <summary>
        /// 如果状态关闭，请输入关闭网站原因
        /// </summary>
        public string CloseInfo { get; set; }

        /// <summary>
        /// 是否删除
        /// </summary>
        public bool IsDel { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public DateTime AddTime { get; set; }

    }
}
