//-----------------------------------------------------------------------
// <copyright file=" CmsVote.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsVote.cs
// * history : Created by T4 09/28/2019 17:26:54
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    /// <summary>
    /// CmsVote Entity Model
    /// </summary>
    [Table("cms_vote")]
    public partial class CmsVote
    {
        /// <summary>
        /// 主键自增
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// 所属栏目ID
        /// </summary>
        public int ColumnId { get; set; }

        /// <summary>
        /// 投票标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 投票副标题
        /// </summary>
        public string SubTitle { get; set; }

        /// <summary>
        /// 选项总数
        /// </summary>
        public int ItemSum { get; set; }

        /// <summary>
        /// 投票总数
        /// </summary>
        public int VoteSum { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public bool Options { get; set; }

        /// <summary>
        /// 投票类型
        /// </summary>
        public int VoteType { get; set; }

        /// <summary>
        /// 宣传图
        /// </summary>
        public string ImgUrl { get; set; }

        /// <summary>
        /// 时间限制
        /// </summary>
        public bool IsTime { get; set; }

        /// <summary>
        /// 开始时间
        /// </summary>
        public DateTime BeginDate { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public DateTime EndDate { get; set; }

        /// <summary>
        /// 投票简介
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// 发布时间
        /// </summary>
        public DateTime AddDate { get; set; }

    }
}
