//-----------------------------------------------------------------------
// <copyright file=" SysAppsetting.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysAppsetting.cs
// * history : Created by T4 09/28/2019 17:26:54
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    /// <summary>
    /// SysAppsetting Entity Model
    /// </summary>
    [Table("sys_appsetting")]
    public partial class SysAppsetting
    {
        /// <summary>
        /// 
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 安卓版本号
        /// </summary>
        public string AndroidVersion { get; set; }

        /// <summary>
        /// 更新文件
        /// </summary>
        public string AndroidFile { get; set; }

        /// <summary>
        /// Ios版本号
        /// </summary>
        public string IosVersion { get; set; }

        /// <summary>
        /// Ios更新文件地址
        /// </summary>
        public string IosFile { get; set; }

        /// <summary>
        /// Ios审核开关  0=关/1=开
        /// </summary>
        public int IosAudit { get; set; }

        /// <summary>
        /// 删除 0=不删除/1=删除
        /// </summary>
        public bool IsDel { get; set; }

        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime UpdateDate { get; set; }

    }
}
