//-----------------------------------------------------------------------
// <copyright file=" WxSetting.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: WxSetting.cs
// * history : Created by T4 09/28/2019 17:26:54
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Models.Models
{
    /// <summary>
    /// WxSetting Entity Model
    /// </summary>
    [Table("wx_setting")]
    public partial class WxSetting
    {
        /// <summary>
        /// 自动增长
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// 公众号名称
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 公众平台微信号
        /// </summary>
        public string Account { get; set; }

        /// <summary>
        /// 公众号原始ID
        /// </summary>
        public string OriginalId { get; set; }

        /// <summary>
        /// ToKen
        /// </summary>
        public string AppId { get; set; }

        /// <summary>
        /// AppSecret
        /// </summary>
        public string AppSecret { get; set; }

        /// <summary>
        /// 公众号类型
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// 公众号图片
        /// </summary>
        public string Cover { get; set; }

        /// <summary>
        /// 公众号二维码
        /// </summary>
        public string QrCode { get; set; }

        /// <summary>
        /// 状态
        /// </summary>
        public bool Status { get; set; }

        /// <summary>
        /// 自定义菜单Json
        /// </summary>
        public string MenuJson { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime AddDate { get; set; }

    }
}
