//-----------------------------------------------------------------------
// <copyright file=" BbsComment.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BbsComment.cs
// * history : Created by T4 09/28/2019 16:14:43
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// BbsComment Entity Model
    /// </summary>
    [Table("bbs_comment")]
    public class BbsComment
    {
        /// <summary>
        /// 唯一编号 唯一编号
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 所属问题编号 所属问题编号
        /// </summary>
        public string QuestionGuid { get; set; }

        /// <summary>
        /// 所属答案编号 所属答案编号
        /// </summary>
        public string AnswerGuid { get; set; }

        /// <summary>
        /// 用户编号 用户编号
        /// </summary>
        public string UserGuid { get; set; }

        /// <summary>
        /// 审核状态 审核状态
        /// </summary>
        public bool Status { get; set; }

        /// <summary>
        /// 评论内容 评论内容
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 评论时间 评论时间
        /// </summary>
        public DateTime AddTime { get; set; }

    }
}
