//-----------------------------------------------------------------------
// <copyright file=" CmsComment.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsComment.cs
// * history : Created by T4 09/28/2019 16:14:43
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// CmsComment Entity Model
    /// </summary>
    [Table("cms_comment")]
    public class CmsComment
    {
        /// <summary>
        /// 唯一ID
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 归属栏目ID
        /// </summary>
        public string ColumnId { get; set; }

        /// <summary>
        /// 评论人ID
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// 评论人昵称
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// 评论内容
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// 评论时间
        /// </summary>
        public DateTime AddDate { get; set; }

        /// <summary>
        /// 评论类型，如=1文章   2=下载  3=商品
        /// </summary>
        public int Option { get; set; }

        /// <summary>
        /// 如果评论有星，显示星数
        /// </summary>
        public int Star { get; set; }

        /// <summary>
        /// 回复人ID
        /// </summary>
        public string RepUserId { get; set; }

        /// <summary>
        /// 回复人昵称
        /// </summary>
        public string RepUserName { get; set; }

        /// <summary>
        /// 回复时间
        /// </summary>
        public DateTime RepDate { get; set; }

        /// <summary>
        /// 是否审核通过
        /// </summary>
        public bool Audit { get; set; }

    }
}
