//-----------------------------------------------------------------------
// <copyright file=" CmsMessage.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsMessage.cs
// * history : Created by T4 09/28/2019 16:14:43
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// CmsMessage Entity Model
    /// </summary>
    [Table("cms_message")]
    public class CmsMessage
    {
        /// <summary>
        /// 自动标识
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// 栏目ID
        /// </summary>
        public string ColumnId { get; set; }

        /// <summary>
        /// 类型
        /// </summary>
        public int Types { get; set; }

        /// <summary>
        /// 标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 电话号码
        /// </summary>
        public string Mobile { get; set; }

        /// <summary>
        /// 联系邮箱
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// QQ
        /// </summary>
        public string QQ { get; set; }

        /// <summary>
        /// 是否查看
        /// </summary>
        public bool Status { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// 内容
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// 用户ID
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// 用户名称
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string IP { get; set; }

        /// <summary>
        /// 父ID
        /// </summary>
        public int ParentId { get; set; }

        /// <summary>
        /// 回复ID
        /// </summary>
        public int RepId { get; set; }

        /// <summary>
        /// 回复内容
        /// </summary>
        public string RepContent { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime AddDate { get; set; }

        /// <summary>
        /// 回复时间
        /// </summary>
        public DateTime RepDate { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string SiteGuid { get; set; }

    }
}
