//-----------------------------------------------------------------------
// <copyright file=" CmsVoteitem.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsVoteitem.cs
// * history : Created by T4 09/28/2019 16:14:43
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// CmsVoteitem Entity Model
    /// </summary>
    [Table("cms_voteitem")]
    public class CmsVoteitem
    {
        /// <summary>
        /// 主键自增
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// 投票项ID
        /// </summary>
        public int VoteId { get; set; }

        /// <summary>
        /// 投票项
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 投票数
        /// </summary>
        public int VoteSum { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Scale { get; set; }

        /// <summary>
        /// 排序字段
        /// </summary>
        public int Sort { get; set; }

    }
}
