//-----------------------------------------------------------------------
// <copyright file=" CmsVotelog.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsVotelog.cs
// * history : Created by T4 09/28/2019 16:14:43
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// CmsVotelog Entity Model
    /// </summary>
    [Table("cms_votelog")]
    public class CmsVotelog
    {
        /// <summary>
        /// 唯一ID
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 投票ID
        /// </summary>
        public int VoteId { get; set; }

        /// <summary>
        /// 投票项ID
        /// </summary>
        public string ItemId { get; set; }

        /// <summary>
        /// 投票人ID
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// 投票人昵称
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// IP地址
        /// </summary>
        public string Ip { get; set; }

        /// <summary>
        /// 投票时间
        /// </summary>
        public DateTime AddDate { get; set; }

        /// <summary>
        /// 投票详情
        /// </summary>
        public string Summary { get; set; }

    }
}
