using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace T4MysqlDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            //bool serviceModel = false;

            //// 数据库连接
            //var connectionString = @"server=localhost;uid=root;pwd=123456;charset=utf8;";

            //// 需要解析的数据库
            //var database = new List<string> { "fyt_cms" };

            //// 文件版权信息
            //var copyright = DateTime.Now.Year + " xxxx Enterprises All Rights Reserved";
            //var version = Environment.Version;
            //var author = "auto generated by T4";

            ////var manager = Manager1.Create(Host, GenerationEnvironment);
            //var entities = EntityHelper.GetEntities(connectionString, database);
        }
    }
}
