//-----------------------------------------------------------------------
// <copyright file=" SysCode.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysCode.cs
// * history : Created by T4 09/28/2019 16:14:43
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// SysCode Entity Model
    /// </summary>
    [Table("sys_code")]
    public class SysCode
    {
        /// <summary>
        /// 唯一标号Guid
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 字典类型标识
        /// </summary>
        public string ParentGuid { get; set; }

        /// <summary>
        /// 字典值——类型
        /// </summary>
        public string CodeType { get; set; }

        /// <summary>
        /// 字典值——名称
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 字典值——英文名称
        /// </summary>
        public string EnName { get; set; }

        /// <summary>
        /// 字典值——排序
        /// </summary>
        public int Sort { get; set; }

        /// <summary>
        /// 字典值——状态
        /// </summary>
        public bool Status { get; set; }

        /// <summary>
        /// 字典值——描述
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// 字典值——添加时间
        /// </summary>
        public DateTime AddTime { get; set; }

        /// <summary>
        /// 字典值——修改时间
        /// </summary>
        public DateTime EditTime { get; set; }

    }
}
