//-----------------------------------------------------------------------
// <copyright file=" SysMenu.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysMenu.cs
// * history : Created by T4 09/28/2019 16:14:43
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Console4Test
{
    /// <summary>
    /// SysMenu Entity Model
    /// </summary>
    [Table("sys_menu")]
    public class SysMenu
    {
        /// <summary>
        /// 唯一标识Guid
        /// </summary>
        [Key]
        public string Guid { get; set; }

        /// <summary>
        /// 所属站点或公司菜单
        /// </summary>
        public string SiteGuid { get; set; }

        /// <summary>
        /// 菜单父级Guid
        /// </summary>
        public string ParentGuid { get; set; }

        /// <summary>
        /// 父级菜单名称
        /// </summary>
        public string ParentName { get; set; }

        /// <summary>
        /// 菜单名称
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 菜单名称标识
        /// </summary>
        public string NameCode { get; set; }

        /// <summary>
        /// 所属父级的集合
        /// </summary>
        public string ParentGuidList { get; set; }

        /// <summary>
        /// 菜单深度
        /// </summary>
        public int Layer { get; set; }

        /// <summary>
        /// 菜单Url
        /// </summary>
        public string Urls { get; set; }

        /// <summary>
        /// 菜单图标Class
        /// </summary>
        public string Icon { get; set; }

        /// <summary>
        /// 菜单排序
        /// </summary>
        public int Sort { get; set; }

        /// <summary>
        /// 菜单状态 true=正常 false=不显示
        /// </summary>
        public bool Status { get; set; }

        /// <summary>
        /// 菜单按钮功能的值，关联Code
        /// </summary>
        public string BtnFunJson { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime EditTime { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime AddTIme { get; set; }

    }
}
