//-----------------------------------------------------------------------
// <copyright file=" IBbsQuestionsServices.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: IBbsQuestionsServices.cs
// * history : Created by T4 09/28/2019 22:30:17
// </copyright>
//-----------------------------------------------------------------------
using IServices.Base;
using Models.Models;

namespace IServices
{
    /// <summary>
    /// IBbsQuestionsServices
    /// </summary>
    public partial interface IBbsQuestionsServices : IBaseServices<BbsQuestions>
    {
    }
}
