//-----------------------------------------------------------------------
// <copyright file=" ISysLogRepository.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: ISysLogRepository.cs
// * history : Created by T4 09/28/2019 22:20:55
// </copyright>
//-----------------------------------------------------------------------
using IRepository.Base;
using Models.Models;

namespace IRepository
{
    /// <summary>
    /// ISysLogRepository
    /// </summary>
	public partial interface ISysLogRepository : IBaseRepository<SysLog>
    {
    }
}
