//-----------------------------------------------------------------------
// <copyright file=" BbsCommentServices.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BbsCommentServices.cs
// * history : Created by T4 09/28/2019 22:25:13
// </copyright>
//-----------------------------------------------------------------------
using IRepository;
using IServices;
using Models.Models;
using Services.Base;

namespace Services
{
    /// <summary>
    /// BbsCommentServices
    /// </summary>
    public partial class BbsCommentServices : BaseServices<BbsComment>, IBbsCommentServices
    {
        IBbsCommentRepository dal;

        public BbsCommentServices(IBbsCommentRepository dal)
        {
            this.dal = dal;
            base.baseDal = dal;
        }
    }
}
