//-----------------------------------------------------------------------
// <copyright file=" CmsArticleServices.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsArticleServices.cs
// * history : Created by T4 09/28/2019 22:25:13
// </copyright>
//-----------------------------------------------------------------------
using IRepository;
using IServices;
using Models.Models;
using Services.Base;

namespace Services
{
    /// <summary>
    /// CmsArticleServices
    /// </summary>
    public partial class CmsArticleServices : BaseServices<CmsArticle>, ICmsArticleServices
    {
        ICmsArticleRepository dal;

        public CmsArticleServices(ICmsArticleRepository dal)
        {
            this.dal = dal;
            base.baseDal = dal;
        }
    }
}
