//-----------------------------------------------------------------------
// <copyright file=" CmsVotelogServices.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: CmsVotelogServices.cs
// * history : Created by T4 09/28/2019 22:25:13
// </copyright>
//-----------------------------------------------------------------------
using IRepository;
using IServices;
using Models.Models;
using Services.Base;

namespace Services
{
    /// <summary>
    /// CmsVotelogServices
    /// </summary>
    public partial class CmsVotelogServices : BaseServices<CmsVotelog>, ICmsVotelogServices
    {
        ICmsVotelogRepository dal;

        public CmsVotelogServices(ICmsVotelogRepository dal)
        {
            this.dal = dal;
            base.baseDal = dal;
        }
    }
}
