//-----------------------------------------------------------------------
// <copyright file=" MemberServices.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: MemberServices.cs
// * history : Created by T4 09/28/2019 22:25:13
// </copyright>
//-----------------------------------------------------------------------
using IRepository;
using IServices;
using Models.Models;
using Services.Base;

namespace Services
{
    /// <summary>
    /// MemberServices
    /// </summary>
    public partial class MemberServices : BaseServices<Member>, IMemberServices
    {
        IMemberRepository dal;

        public MemberServices(IMemberRepository dal)
        {
            this.dal = dal;
            base.baseDal = dal;
        }
    }
}
