//-----------------------------------------------------------------------
// <copyright file=" BbsAnswerRepository.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BbsAnswerRepository.cs
// * history : Created by T4 09/28/2019 22:21:11
// </copyright>
//-----------------------------------------------------------------------
using IRepository;
using Models.Models;
using Repository.Base;

namespace Repository
{
    /// <summary>
    /// BbsAnswerRepository
    /// </summary>
	public partial class BbsAnswerRepository : BaseRepository<BbsAnswer>, IBbsAnswerRepository
    {
    }
}
