//-----------------------------------------------------------------------
// <copyright file=" SysCodeRepository.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: SysCodeRepository.cs
// * history : Created by T4 09/28/2019 22:21:11
// </copyright>
//-----------------------------------------------------------------------
using IRepository;
using Models.Models;
using Repository.Base;

namespace Repository
{
    /// <summary>
    /// SysCodeRepository
    /// </summary>
	public partial class SysCodeRepository : BaseRepository<SysCode>, ISysCodeRepository
    {
    }
}
