//-----------------------------------------------------------------------
// <copyright file=" BbsNoticeMap.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BbsNoticeMap.cs
// * history : Created by T4 09/28/2019 17:26:34
// </copyright>
//-----------------------------------------------------------------------
using Models.Models;
using System.Data.Entity.ModelConfiguration;

namespace Models.Maps
{
    /// <summary>
    /// BbsNoticeMap
    /// </summary>
    public partial class BbsNoticeMap : EntityTypeConfiguration<BbsNotice>
    {
        public BbsNoticeMap()
        {
            this.HasKey(p => p.Guid);
            this.HasKey(p => p.UserGuid);
            this.HasKey(p => p.Types);
            this.HasKey(p => p.IsRead);
            this.HasKey(p => p.AddTime);
        }
    }
}
